FROM node:22-slim AS base
WORKDIR /app

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

RUN apt-get update -y && apt-get install -y openssl
RUN corepack enable && pnpm install prisma @prisma/adapter-pg @prisma/client dotenv dayjs

FROM base AS prisma
WORKDIR /app

COPY package.json pnpm-lock.yaml .npmrc prisma.config.ts ./
COPY server/prisma/ ./server/prisma/
COPY shared/utils/ ./shared/utils/
COPY server/utils/dayjs.ts ./server/utils/dayjs.ts
COPY --chmod=0755 docker-entrypoint.sh .

RUN pnpm prisma generate

ENTRYPOINT ["/app/docker-entrypoint.sh"]
