FROM node:22-slim AS base
WORKDIR /app

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

RUN apt-get update -y && apt-get install -y openssl
RUN corepack enable && pnpm install prisma @prisma/adapter-pg @prisma/client dotenv

FROM base AS prisma
WORKDIR /app

COPY package.json prisma.config.ts ./
COPY server/prisma/ ./server/prisma/
COPY --chmod=0755 docker-entrypoint.sh .

RUN pnpm prisma generate

ENTRYPOINT ["/app/docker-entrypoint.sh"]
