export const PERMISSIONS: readonly string[] = [
  "participants.read",
  "participants.read.sensitive",
  "participants.check_in",
  "participants.update",
  "participants.update.sensitive",
  "participants.delete",
  "participants.export",
  "participants.export.sensitive",
  "teams.read",
  "teams.update",
  "teams.delete",
  "teams.export",
  "guests.read",
  "guests.create",
  "guests.update",
  "guests.delete",
  "guests.export",
  "sponsors.read",
  "sponsors.create",
  "sponsors.update",
  "sponsors.delete",
  "sponsors.export",
  "broadcasts.send",
  "submissionRequests.read",
  "submissionRequests.create",
  "submissionRequests.update",
  "submissionRequests.delete",
  "submissionRequests.export",
  "rooms.read",
  "rooms.create",
  "rooms.update",
  "rooms.assign.team",
  "rooms.delete",
  "rooms.export",
  "badges.print",
  "admins.read",
  "admins.create",
  "admins.update",
  "admins.delete",
  "roles.read",
  "roles.create",
  "roles.update",
  "roles.delete",
] as const;

export type Permission = typeof PERMISSIONS[number];
