/**
 * This file has been partially generated by AI, for the centroid calculation and the text fitting logic.
 */
import PDFDocument from "pdfkit";
import qr from "qrcode";
import type { Prisma } from "#server/prisma/generated/prisma/browser";

type Participant = Prisma.ParticipantGetPayload<{
  include: {
    user: true,
    team: true,
  }
}>

type LayoutCircleOptions = {
  pos: Coordinates;
  radius: number;
};

type Coordinates = [x: number, y: number];

interface TextLine {
  text: string;
  fontSize: number;
  color: string;
  gapAfter?: boolean;
}

interface MeasuredTextLine extends TextLine {
  height: number;
  fittedFontSize: number;
}

interface DrawBadgeTextBlockOptions {
  circle?: LayoutCircleOptions;
  minimumLeftX?: number;
  circleSafeMargin?: number;
  textRightPadding?: number;
  textVerticalPadding?: number;
  baseTextGap?: number;
}

//const rolesColors = {
//  "Participant": "#227d50",
//  "Organisateur": "#0000ff",
//  "Coach": "#ffa500",
//  "Jury": "#800080",
//  "Sponsor": "#008000",
//  "Invité": "#008080",
//  "Sans équipe": "#ff0000",
//};

//region Utils
function cmToPoints(cm: number): number {
  return cm * 28.3465;
}

function getDefaultBadgeCircle(size: Coordinates): LayoutCircleOptions {
  const [, pageHeight] = size;
  const pos: Coordinates = [7.5, 5];

  return {
    pos,
    radius: pageHeight / 2.7,
  };
}

/**
 * Calculates the centroid of the visible area of a circle, given the page size and circle parameters.
 *
 * (100% AI-generated, I am NOT *that* good at math)
 *
 * @param pageSize The size of the page as [width, height] in points
 * @param circleCenter The center of the circle as [x, y] in points
 * @param radius The radius of the circle in points
 * @param steps The number of vertical strips to divide the circle into for numerical integration (higher = more accurate but slower)
 * @returns The coordinates of the centroid of the visible area of the circle, adjusted for page boundaries
 */
function visibleCircleCentroid(pageSize: Coordinates, circleCenter: Coordinates, radius: number, steps = 2000): Coordinates {
  const [pageWidth, pageHeight] = pageSize;
  const [cx, cy] = circleCenter;
  const r = radius;

  const xStart = Math.max(0, cx - r);
  const xEnd = Math.min(pageWidth, cx + r);
  const dx = (xEnd - xStart) / steps;

  let area = 0;
  let momentX = 0;
  let momentY = 0;

  for (let i = 0; i < steps; i++) {
    const x = xStart + (i + 0.5) * dx;
    const localX = x - cx;
    const h = Math.sqrt(Math.max(0, r * r - localX * localX));

    const yMin = Math.max(0, cy - h);
    const yMax = Math.min(pageHeight, cy + h);

    if (yMax <= yMin) continue;

    const stripArea = (yMax - yMin) * dx;
    area += stripArea;

    momentX += x * stripArea;
    momentY += 0.5 * (yMax * yMax - yMin * yMin) * dx;
  }

  return [momentX / area, momentY / area];
}

/**
 * Draws a block of text centered horizontally between fromX and toX at the specified y coordinate.
 *
 * @param doc The PDFDocument instance to draw on
 * @param fontSize The font size to use for the text
 * @param text The text to draw
 * @param y The y coordinate to draw the text at
 * @param fromX The left boundary for centering the text
 * @param toX The right boundary for centering the text
 */
function centerTextHorizontally(doc: PDFKit.PDFDocument, fontSize: number, text: string, y: number, fromX: number, toX: number) {
  doc.fontSize(fontSize).text(text, fromX, y, {
    width: toX - fromX,
    align: "center",
  });
}

/**
 * Calculates the height of a block of text when rendered with the specified font size and constrained to a width defined by fromX and toX.
 *
 * @param doc The PDFDocument instance to use for measuring the text
 * @param fontSize The font size to use for measuring the text
 * @param text The text to measure
 * @param fromX The left boundary for the text width constraint
 * @param toX The right boundary for the text width constraint
 * @returns The height of the text block in points
 */
function getTextHeight(doc: PDFKit.PDFDocument, fontSize: number, text: string, fromX: number, toX: number) {
  doc.fontSize(fontSize);
  return doc.heightOfString(text, {
    width: toX - fromX,
    align: "center",
  });
}

/**
 * Calculates the total height of a block of text lines, including gaps between lines.
 *
 * @param lines An array of measured text lines, each with its own height and optional gapAfter property
 * @param textGap The base gap to apply between lines that don't explicitly disable it with gapAfter = false
 * @returns The total height of the text block, including line heights and gaps
 */
function getTotalTextHeight(lines: MeasuredTextLine[], textGap: number): number {
  return lines.reduce((sum, line, index) => {
    // Add a gap after each line except the last one, and if the line doesn't explicitly disable it
    const hasGapAfter = index < lines.length - 1 && (line.gapAfter ?? true);
    return sum + line.height + (hasGapAfter ? textGap : 0);
  }, 0);
}

/**
 * Measures the height of each text line when rendered with a given font scale, and returns an array of measured text lines with their fitted font size and height.
 * This is used to find the best font scale that allows all lines to fit within a certain height constraint.
 *
 * @param doc The PDFDocument instance to use for measuring the text
 * @param lines An array of text lines to measure, each with its own font size and text content
 * @param fromX The left boundary for the text width constraint
 * @param toX The right boundary for the text width constraint
 * @param fontScale The scale factor to apply to the original font sizes of the lines for measurement (e.g. 1 for original size, 0.8 for 80% size)
 * @returns An array of measured text lines, i.e. TextLine & fittedFontSize and height based on the given font scale
 */
function measureTextLines(doc: PDFKit.PDFDocument, lines: TextLine[], fromX: number, toX: number, fontScale: number): MeasuredTextLine[] {
  return lines.map(line => {
    const fittedFontSize = line.fontSize * fontScale;
    return {
      ...line,
      fittedFontSize,
      height: getTextHeight(doc, fittedFontSize, line.text, fromX, toX),
    };
  });
}

/**
 * Finds the best font scale to fit a block of text lines within a specified maximum height constraint, by iteratively
 * measuring the text height at different scales and returning the first one that fits.
 *
 * If no scale allows the text to fit, it applies an emergency scale based on the overflow ratio to try to fit as much as possible.
 *
 * @param doc The PDFDocument instance to use for measuring the text
 * @param lines An array of text lines to fit
 * @param fromX The left boundary for the text width constraint
 * @param toX The right boundary for the text width constraint
 * @param maxHeight The maximum allowed height for the block of text lines, including gaps
 * @param baseTextGap The base gap to apply between lines at a scale of 1 (this will be scaled down with the font size)
 * @returns An object containing the fitted lines with their measured heights and font sizes, and the text gap to use between lines
 */
function fitMeasuredTextLines(doc: PDFKit.PDFDocument, lines: TextLine[], fromX: number, toX: number, maxHeight: number, baseTextGap: number) {
  const minimumFontScale = .3;
  const scaleStep = .025;

  let bestFit = {
    fittedLines: measureTextLines(doc, lines, fromX, toX, 1),
    textGap: baseTextGap,
  };

  // We start from a scale of 1 (original font size) and decrease it until we find a scale that allows the text to fit within the maxHeight constraint.
  for (let candidateScale = 1; candidateScale >= minimumFontScale; candidateScale -= scaleStep) {
    const candidateGap = baseTextGap * candidateScale;
    const candidateLines = measureTextLines(doc, lines, fromX, toX, candidateScale);

    bestFit = {
      fittedLines: candidateLines,
      textGap: candidateGap,
    };

    if (getTotalTextHeight(candidateLines, candidateGap) <= maxHeight) {
      return bestFit;
    }
  }

  // If we exit the loop, it means even the minimum font scale is not enough to fit the text within the maxHeight constraint.
  // In this case, we apply an emergency scale based on the overflow ratio to try to fit as much as possible,
  // but we don't go below a certain minimum to avoid making the text unreadable.
  const overflowRatio = maxHeight / getTotalTextHeight(bestFit.fittedLines, bestFit.textGap);
  const emergencyScale = Math.max(.15, minimumFontScale * overflowRatio);

  return {
    fittedLines: measureTextLines(doc, lines, fromX, toX, emergencyScale),
    textGap: baseTextGap * emergencyScale,
  };
}

/**
 * Draws a centered, wrapped and height-fitted block of badge text.
 *
 * @param doc The PDFDocument instance to draw on
 * @param size The size of the page in points
 * @param lines An array of text lines to draw, each with its own font size and color
 * @param options Additional options for drawing the text block, such as circle parameters and padding values
 */
function drawBadgeTextBlock(doc: PDFKit.PDFDocument, size: Coordinates, lines: TextLine[], options: DrawBadgeTextBlockOptions = {}) {
  // Default options
  const {
    circle = getDefaultBadgeCircle(size),
    minimumLeftX = 0,
    circleSafeMargin = cmToPoints(1),
    textRightPadding = cmToPoints(.25),
    textVerticalPadding = cmToPoints(.12),
    baseTextGap = cmToPoints(.3),
  } = options;

  const [pageWidth, pageHeight] = size;
  const circleSafeRightX = circle.pos[0] + circle.radius + circleSafeMargin;
  const textFromX = Math.max(circleSafeRightX, minimumLeftX);
  const textToX = pageWidth - textRightPadding;

  const {
    fittedLines,
    textGap,
  } = fitMeasuredTextLines(doc, lines, textFromX, textToX, pageHeight - (textVerticalPadding * 2), baseTextGap);

  const totalTextHeight = getTotalTextHeight(fittedLines, textGap);

  let currentY = Math.max(textVerticalPadding, (pageHeight - totalTextHeight) / 2);
  for (const [index, line] of fittedLines.entries()) {
    doc.fillColor(line.color);
    centerTextHorizontally(doc, line.fittedFontSize, line.text, currentY, textFromX, textToX);

    const hasGapAfter = index < fittedLines.length - 1 && (line.gapAfter ?? true);
    currentY += line.height + (hasGapAfter ? textGap : 0);
  }
}

//endregion

//region Main functions
/**
 * Creates the common layout for a badge, including the background, the logo circle and the logo itself.
 *
 * @param doc The PDFDocument instance to draw on
 * @param size The size of the page in points
 * @param circle Optional parameters for the logo circle, including its position and radius. If not provided, default values based on the page size will be used.
 */
async function createBadgeLayout(doc: PDFKit.PDFDocument, size: Coordinates, circle = getDefaultBadgeCircle(size)) {
  const [pageWidth, pageHeight] = size;

  doc.addPage({size, margin: 0});

  const primaryColor = "#227d50";
  const bgColor = "#ecfff4";

  doc.rect(0, 0, pageWidth, pageHeight).fillColor(bgColor).fill();

  doc.fillColor(primaryColor);

  //region Logo and circle
  doc.circle((circle.pos)[0], (circle.pos)[1], circle.radius).fill();

  //eslint-disable-next-line @typescript-eslint/no-explicit-any
  const logo = (doc as any).openImage("./public/images/logo.png");
  const logoWidth = circle.radius * .9;
  const logoHeight = logoWidth * (logo.height / logo.width);
  const [logoCenterX, logoCenterY] = visibleCircleCentroid(
    size,
    circle.pos,
    circle.radius,
  );
  const logoPos: Coordinates = [
    logoCenterX - logoWidth / 2,
    logoCenterY - logoHeight / 2,
  ];
  doc.image(logo, logoPos[0], logoPos[1], {
    width: logoWidth,
  });
  //endregion
}

/**
 * Creates a badge for a participant, including the common layout, the QR code and the participant's information text.
 *
 * @param doc The PDFDocument instance to draw on
 * @param participant The participant for whom to create the badge
 * @param size The size of the page in points
 * @returns A boolean indicating whether the participant has a team or not, which can be used for sorting badges with team participants first
 */
async function createParticipantBadge(doc: PDFKit.PDFDocument, participant: Participant, size: Coordinates) {
  const [, pageHeight] = size;

  const primaryColor = "#227d50";
  const bgColor = "#ecfff4";

  await createBadgeLayout(doc, size);

  //region QR Code
  const qrcode = await qr.toBuffer(participant.userId, {margin: 0, color: {light: bgColor}});
  const qrcodeSize = pageHeight * .4;
  const qrcodeMargin = cmToPoints(.25);
  const qrcodePos: Coordinates = [qrcodeMargin, pageHeight - qrcodeSize - qrcodeMargin];
  doc.image(qrcode, qrcodePos[0], qrcodePos[1], {width: qrcodeSize, height: qrcodeSize, align: "center"});
  //endregion

  //region Text
  const qrcodeSafeMargin = cmToPoints(.5);

  // Size constants
  const h1Size = 20;
  const h2Size = 16;
  const h3Size = 14;
  const h4Size = 12;

  const fullName = `${participant.user.firstName} ${participant.user.lastName}`.trim();
  const role = "Participant";

  const textLines: TextLine[] = [
    {text: fullName, fontSize: h1Size, color: primaryColor, gapAfter: false},
    {text: role, fontSize: h2Size, color: primaryColor},
    participant.team
      ? {text: `Team ${participant.team.name}`, fontSize: h3Size, color: primaryColor}
      : {text: "Sans équipe", fontSize: h3Size, color: "#ff0000"},
    // We use array destructuring to avoir having to deal with a null or undefined value afterwards
    ...(participant.school
      ? [{text: participant.school, fontSize: h4Size, color: primaryColor}]
      : []),
  ];

  drawBadgeTextBlock(doc, size, textLines, {
    minimumLeftX: qrcodePos[0] + qrcodeSize + qrcodeSafeMargin,
  });
  doc.fillColor(primaryColor);
  //endregion

  return !!participant.team;
}

/**
 * Renders a PDF document containing badges for a list of participants, with team participants rendered first.
 *
 * @param participants An array of participants to render badges for
 * @returns A PDFDocument instance containing the rendered badges for all participants
 */
export async function renderParticipantsBadges(participants: Participant[]): Promise<PDFKit.PDFDocument> {
  const size: Coordinates = [cmToPoints(10), cmToPoints(5)];

  const doc = new PDFDocument({
    size,
    margin: 0,
    autoFirstPage: false,
    pdfVersion: "1.7",
    info: {
      Title: "Badges des participants",
      Author: "CSLabs",
      Subject: `Hackathon ${new Date().getFullYear()}`,
    },
    displayTitle: true,
  });

  const noTeamParticipants = participants.filter(p => !p.team);
  const teamParticipants = participants.filter(p => !!p.team);

  for (const participant of teamParticipants) {
    await createParticipantBadge(doc, participant, size);
  }
  for (const participant of noTeamParticipants) {
    await createParticipantBadge(doc, participant, size);
  }

  doc.end();

  return doc;
}

//endregion
