name: Build and deploy documentation

on:
  push:
    branches: [ main, deploy ]
    paths: [ "docs/**" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

env:
  NODE_VERSION: 22

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Node + pnpm and install dependencies
        working-directory: ./docs
        uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup pages
        working-directory: ./docs
        uses: actions/configure-pages@v4
      - name: Install dependencies
        working-directory: ./docs
        run: pnpm install --frozen-lockfile
      - name: Build documentation
        working-directory: ./docs
        run: pnpm run build
      - name: Deploy to GitHub Pages
        working-directory: ./docs
        uses: actions/upload-pages-artifact@v3
        with:
          path: .vitepress/dist
  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
